name: teno_debug
description: A set of utilities for debugging in Dart
version: 0.0.1
repository: https://github.com/hnvcam/teno_debug

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  logging: any
  bloc: any

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
